language: csharp
dist: xenial
dotnet: 3.1
#mono: none

install: 
- bash ./cicd.sh install

script:
- bash ./cicd.sh build
#- bash ./cicd.sh test

deploy:
  provider: script
  #skip_cleanup: true
  script: bash ./cicd.sh deploy
  on:
    branch: release  
    tags: true
